java -jar BrainConvert.jar p1_config.txt 
java -jar BrainConvert.jar p2_config.txt 
java -jar BrainConvert.jar p3_config.txt 
java -jar BrainConvert.jar p4_config.txt 
java -jar BrainConvert.jar p5_config.txt 
java -jar BrainConvert.jar p6_config.txt 
java -jar BrainConvert.jar p7_config.txt 
java -jar BrainConvert.jar p8_config.txt 
java -jar BrainConvert.jar p9_config.txt 
java -jar BrainConvert.jar p10_config.txt